version: 2

updates:
  # 1) GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      time: "04:00"
      timezone: "America/Panama"
    target-branch: "main"
    labels: ["ci", "infra", "dependencies"]
    open-pull-requests-limit: 5
    rebase-strategy: auto
    groups:
      gh-actions-minor:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # 2) NuGet (escaneo recursivo bajo /src para futuros proyectos)
  - package-ecosystem: nuget
    directory: "/src"
    schedule:
      interval: monthly
      time: "04:30"
      timezone: "America/Panama"
    target-branch: "main"
    labels: ["backend", "infra", "dependencies"]
    open-pull-requests-limit: 10
    rebase-strategy: auto
    versioning-strategy: increase
    groups:
      nuget-minor:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Ejemplos de ignores (opcional):
    # ignore:
    #   - dependency-name: "Microsoft.NET.Test.Sdk"
    #     update-types: ["version-update:semver-major"]
    #   - dependency-name: "Moq"
    #     versions: [">=5.a"]  # ignora pre-releases o líneas mayores