version: 2

updates:
  # 1) GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      day: monday
      time: "04:00"
      timezone: "America/Panama"
    target-branch: "main"
    labels: ["ci", "infra", "dependencies"]
    open-pull-requests-limit: 5
    rebase-strategy: auto
    groups:
      gh-actions-minor:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # 2) NuGet (escanea recursivo debajo de /src para futuros proyectos)
  - package-ecosystem: nuget
    directory: "/src"
    schedule:
      interval: monthly
      day: monday
      time: "04:30"
      timezone: "America/Panama"
    target-branch: "main"
    labels: ["backend", "dependencies"]
    open-pull-requests-limit: 10
    rebase-strategy: auto
    versioning-strategy: increase
    groups:
      nuget-minor:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"