name-template: "SuiteMDI-EduSQL v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

# Decide SemVer bump based on labels
version-resolver:
  major:
    labels:
      - major
      - breaking-change
  minor:
    labels:
      - minor
      - enhancement
      - feature
  patch:
    labels:
      - patch
      - bug
      - docs
      - infra
      - task
      - chore
      - ci
      - security
      - dependencies
      - sql

# Exclude PRs with these labels from the notes
exclude-labels:
  - skip-changelog
  - wip

# Group PRs by category (order matters)
categories:
  - title: "⚠️ Breaking changes"
    labels: ["breaking-change"]
  - title: "🚀 Features"
    labels: ["enhancement", "feature"]
  - title: "🐞 Fixes"
    labels: ["bug"]
  - title: "🔐 Security"
    labels: ["security"]
  - title: "🧩 SQL"
    labels: ["sql"]
  - title: "🧪 Tests"
    labels: ["test", "tests"]
  - title: "🔧 CI / CD"
    labels: ["ci"]
  - title: "⬆️ Dependencies"
    labels: ["dependencies"]
  - title: "📚 Docs"
    labels: ["docs"]
  - title: "🧰 Chores / Infra"
    labels: ["infra", "task", "chore", "config"]

# How each PR entry is rendered
change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"

# Sorting and presentation
sort-by: "merged_at"
sort-direction: "descending"
categorize-prs: true

template: |
  ## 📦 Release: SuiteMDI-EduSQL v$RESOLVED_VERSION

  **Compare:** $PREVIOUS_TAG → $NEXT_TAG

  ### Changes
  $CHANGES

  ---
  **Notes**
  - See **README** and **CHANGELOG** for setup and usage.
  - PRs labeled `skip-changelog` or `wip` are excluded automatically.