name-template: "SuiteMDI-EduSQL v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

# Decide SemVer bump based on labels
version-resolver:
  major:
    labels:
      - major
      - breaking-change
  minor:
    labels:
      - minor
      - enhancement
      - feature
  patch:
    labels:
      - patch
      - bug
      - docs
      - infra
      - task

# Exclude PRs with these labels from the notes
exclude-labels:
  - skip-changelog
  - wip

# Group PRs by category
categories:
  - title: "🚀 Features"
    labels: ["enhancement", "feature"]
  - title: "🐞 Fixes"
    labels: ["bug"]
  - title: "📚 Docs"
    labels: ["docs"]
  - title: "🧰 Chores / Infra"
    labels: ["infra", "task"]

# How each PR entry is rendered
change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"

# Sorting and presentation
sort-by: "merged_at"
sort-direction: "descending"
categorize-prs: true

template: |
  ## 📦 Release: SuiteMDI-EduSQL v$RESOLVED_VERSION

  **Compare:** $PREVIOUS_TAG → $NEXT_TAG

  ### Changes
  $CHANGES

  ---
  **Notes**
  - See **README** and **CHANGELOG** for setup and usage.
  - PRs labeled `skip-changelog` or `wip` are excluded automatically.