name-template: "SuiteMDI-EduSQL v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels: ["enhancement", "feature"]
  - title: "🐞 Fixes"
    labels: ["bug"]
  - title: "🧰 Chores/Infra"
    labels: ["infra", "task"]
  - title: "📚 Docs"
    labels: ["docs"]
change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"
template: |
  ## Cambios
  $CHANGES

  ## Notas
  - Revisa README y CHANGELOG para instrucciones.