name: "🐞 Bug report"
description: Reporta un error reproducible
labels: ["bug"]
body:
  - type: textarea
    id: steps
    attributes:
      label: Pasos para reproducir
      description: Lista numerada de pasos
      placeholder: "1) ...\n2) ...\n3) ..."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Resultado esperado
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Resultado actual
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: Entorno
      placeholder: "VS2022, Docker SQL 2022, Windows 11..."