name: "🐞 Bug report"
description: Reportar un error
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: ¿Qué pasó?
      description: Describe el bug y lo esperado
      placeholder: "Sucede X, pero debería suceder Y…"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Pasos para reproducir
      placeholder: "1) … 2) …"
  - type: input
    id: env
    attributes:
      label: Entorno
      placeholder: "VS 2022 ES, Docker SQL 2022, Windows 10/11…"