name: "✨ Feature request"
description: Propón una mejora o nueva función
labels: ["enhancement"]
body:
  - type: textarea
    id: desc
    attributes:
      label: Descripción
      placeholder: "¿Qué problema resuelve? ¿Qué aporta?"
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Alcance
      placeholder: "Qué incluye / qué no incluye"
  - type: textarea
    id: acceptance
    attributes:
      label: Criterios de aceptación
      placeholder: "Dado ... Cuando ... Entonces ..."