name: "✨ Feature request"
description: Solicitar una mejora o nueva funcionalidad
labels: ["enhancement"]
body:
  - type: textarea
    id: value
    attributes:
      label: Valor de la mejora
      placeholder: "¿Qué aporta? ¿A quién beneficia?"
      description: Describe el problema a resolver o la oportunidad
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Alcance propuesto
      placeholder: "Incluye/No incluye…"