name: "🧮 SQL change"
description: Cambios que afectan a la base de datos (scripts, SPs, tablas)
labels: ["sql"]
body:
  - type: input
    id: title
    attributes:
      label: Título breve
      placeholder: "Modificar prValidarUsuario para devolver @@ROWCOUNT"
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Alcance (Incluye / No incluye)
      placeholder: |
        Incluye:
        - Ajuste en script 02
        - Comentarios de pruebas unitarias
        No incluye:
        - Cambios en UI
    validations:
      required: true
  - type: textarea
    id: migration
    attributes:
      label: Migración / impacto
      description: ¿Rompe compatibilidad? ¿Requiere reseed, backup o downtime?
      placeholder: "No rompe. Requiere ejecutar script 02 y volver a correr pruebas 20_unitarias/*"
  - type: checkboxes
    id: impact
    attributes:
      label: Impacto
      options:
        - label: Afecta a datos existentes
        - label: Requiere rollback plan
        - label: Requiere actualización de README/CHANGELOG
  - type: textarea
    id: tests
    attributes:
      label: Pruebas
      placeholder: "Añadir tests en db_test/20_unitarias/ y referenciarlos en RUN_ALL.sql"
  - type: textarea
    id: notes
    attributes:
      label: Notas técnicas
      placeholder: "Justificación del cambio, índices considerados, riesgos, etc."