name: "🧩 Task"
description: Tarea técnica o documentación
labels: ["task"]
body:
  - type: textarea
    id: goal
    attributes:
      label: Objetivo
      placeholder: "Qué se hará y por qué"
    validations:
      required: true
  - type: textarea
    id: checklist
    attributes:
      label: Checklist
      placeholder: "- [ ] Paso 1\n- [ ] Paso 2"