name: "🧩 Task"
description: Tarea técnica o de mantenimiento
labels: ["task"]
body:
  - type: textarea
    id: todo
    attributes:
      label: Checklist
      placeholder: "- [ ] Subtarea 1\n- [ ] Subtarea 2"
  - type: textarea
    id: acceptance
    attributes:
      label: Criterios de aceptación
      placeholder: "Se considera done cuando…"