name: Pull Request Labeler

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: pr-labeler-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  triage:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    steps:
      - name: Apply labels based on paths
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          sync-labels: true
