name: Pull Request Labeler

on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: read
  pull-requests: write   # requerido para aplicar labels

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Apply labels based on paths
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml