name: Release Drafter

on:
  push:
    branches: [ "main" ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
      - labeled
      - unlabeled
      - closed
  workflow_dispatch: {}   # <-- opcional: disparo manual

permissions:
  contents: write
  pull-requests: read

concurrency:
  group: release-drafter-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Update release draft
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml   # <-- solo el nombre del archivo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}