name: Release Drafter

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}   # ejecución manual opcional

permissions:
  contents: write
  pull-requests: read

concurrency:
  group: release-drafter-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Update release draft
        uses: release-drafter/release-drafter@v6
        with:
          config-name: .github/release-drafter.yml   # ruta explícita
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
